name: Build Platform

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        type: choice
        options:
          - android
          - ios
          - web
          - windows
          - macos
          - linux
          - all
      build_type:
        description: 'Build type'
        required: true
        type: choice
        options:
          - debug
          - release
      upload_artifact:
        description: 'Upload as artifact'
        required: true
        type: boolean
        default: true

env:
  FLUTTER_VERSION: '3.24.5'

jobs:
  build:
    name: Build ${{ inputs.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
          - platform: ios
            os: macos-latest
          - platform: web
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-latest
          - platform: linux
            os: ubuntu-latest
      fail-fast: false
    if: inputs.platform == 'all' || inputs.platform == matrix.platform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java (Android only)
        if: matrix.platform == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Build Android APK
        if: matrix.platform == 'android'
        run: flutter build apk --${{ inputs.build_type }}

      - name: Build Android App Bundle
        if: matrix.platform == 'android' && inputs.build_type == 'release'
        run: flutter build appbundle --release

      - name: Build iOS
        if: matrix.platform == 'ios'
        run: flutter build ios --${{ inputs.build_type }} --no-codesign

      - name: Build Web
        if: matrix.platform == 'web'
        run: flutter build web --${{ inputs.build_type }}

      - name: Build Windows
        if: matrix.platform == 'windows'
        run: flutter build windows --${{ inputs.build_type }}

      - name: Build macOS
        if: matrix.platform == 'macos'
        run: flutter build macos --${{ inputs.build_type }}

      - name: Build Linux
        if: matrix.platform == 'linux'
        run: flutter build linux --${{ inputs.build_type }}

      - name: Upload Android APK
        if: matrix.platform == 'android' && inputs.upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk-${{ inputs.build_type }}
          path: build/app/outputs/flutter-apk/app-${{ inputs.build_type }}.apk

      - name: Upload Android AAB
        if: matrix.platform == 'android' && inputs.build_type == 'release' && inputs.upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab-release
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Upload iOS Build
        if: matrix.platform == 'ios' && inputs.upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-${{ inputs.build_type }}
          path: build/ios/iphoneos/Runner.app

      - name: Upload Web Build
        if: matrix.platform == 'web' && inputs.upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-${{ inputs.build_type }}
          path: build/web

      - name: Upload Windows Build
        if: matrix.platform == 'windows' && inputs.upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ inputs.build_type }}
          path: build/windows/x64/runner/${{ inputs.build_type == 'release' && 'Release' || 'Debug' }}

      - name: Upload macOS Build
        if: matrix.platform == 'macos' && inputs.upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ inputs.build_type }}
          path: build/macos/Build/Products/${{ inputs.build_type == 'release' && 'Release' || 'Debug' }}

      - name: Upload Linux Build
        if: matrix.platform == 'linux' && inputs.upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-${{ inputs.build_type }}
          path: build/linux/x64/${{ inputs.build_type }}/bundle
